import type { Db } from "../db.ts";

/**
 * Consolidated PostgreSQL baseline — recreates the end-state schema produced by
 * the 53 SQLite migrations (decision #41: fresh PG baseline, frozen SQLite
 * history). Parity choices (decision: keep app SQL identical across engines):
 *   - generated ids are 32-bit `integer` → returned as JS `number`
 *   - booleans stored as `integer` 0/1
 *   - timestamps stored as `text` in `YYYY-MM-DD HH:MM:SS` form
 *
 * Column order mirrors the SQLite end state; tables are ordered so foreign-key
 * targets are created first.
 */

export const id = "001_pg_baseline";

const NOW = "to_char((now() at time zone 'utc'), 'YYYY-MM-DD HH24:MI:SS')";

const STATEMENTS: string[] = [
  // ── conversations (no FK) ──
  `CREATE TABLE IF NOT EXISTS conversations (
     id                                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     task_id                                 integer NULL,
     parent_conversation_id                  integer NULL,
     forked_at_message_id                    integer NULL,
     model                                   text NULL,
     last_engine_type                        text NULL,
     decisions_injected_after_compaction_id  integer NULL,
     sampling_preset_override                text NULL,
     model_params                            text NULL
   )`,

  // ── boards (no FK) ──
  `CREATE TABLE IF NOT EXISTS boards (
     id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     workspace_key        text NOT NULL DEFAULT 'default',
     name                 text NOT NULL,
     workflow_template_id text NOT NULL,
     project_keys         text NOT NULL DEFAULT '[]',
     created_at           text NOT NULL DEFAULT (${NOW})
   )`,

  // ── tasks (refs boards, conversations) ──
  `CREATE TABLE IF NOT EXISTS tasks (
     id                        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     board_id                  integer NOT NULL REFERENCES boards(id),
     project_key               text NOT NULL DEFAULT 'unknown',
     title                     text NOT NULL,
     description               text NOT NULL DEFAULT '',
     workflow_state            text NOT NULL DEFAULT 'backlog',
     execution_state           text NOT NULL DEFAULT 'idle',
     conversation_id           integer REFERENCES conversations(id),
     current_execution_id      integer,
     retry_count               integer NOT NULL DEFAULT 0,
     created_from_task_id       integer,
     created_from_execution_id integer,
     created_at                text NOT NULL DEFAULT (${NOW}),
     shell_auto_approve        integer NOT NULL DEFAULT 0,
     approved_commands         text NOT NULL DEFAULT '[]',
     position                  double precision NOT NULL DEFAULT 0,
     needs_column_prompt       integer NOT NULL DEFAULT 0,
     enabled_mcp_tools         text NULL
   )`,

  // ── executions (no declared FK) ──
  `CREATE TABLE IF NOT EXISTS executions (
     id                           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     task_id                      integer NULL,
     conversation_id              integer NULL,
     from_state                   text NOT NULL DEFAULT '',
     to_state                     text NOT NULL DEFAULT '',
     prompt_id                    text,
     status                       text NOT NULL DEFAULT 'running',
     attempt                      integer NOT NULL DEFAULT 1,
     started_at                   text NOT NULL DEFAULT (${NOW}),
     finished_at                  text,
     summary                      text,
     details                      text,
     cost_estimate                double precision,
     input_tokens                 integer,
     output_tokens                integer,
     cache_creation_input_tokens  integer,
     cache_read_input_tokens      integer
   )`,

  // ── conversation_messages (refs conversations) ──
  `CREATE TABLE IF NOT EXISTS conversation_messages (
     id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     task_id         integer NULL,
     conversation_id integer NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
     type            text NOT NULL,
     role            text,
     content         text NOT NULL DEFAULT '',
     metadata        text,
     created_at      text NOT NULL DEFAULT (${NOW})
   )`,

  // ── decision_batches / records / revisions ──
  `CREATE TABLE IF NOT EXISTS decision_batches (
     id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     conversation_id integer NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
     label           text,
     created_at      text NOT NULL DEFAULT (${NOW})
   )`,
  `CREATE TABLE IF NOT EXISTS decision_records (
     id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     conversation_id integer NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
     batch_id        integer REFERENCES decision_batches(id) ON DELETE SET NULL,
     question        text NOT NULL,
     answer          text NOT NULL,
     weight          text NOT NULL DEFAULT 'medium' CHECK (weight IN ('critical', 'medium', 'easy')),
     notes           text,
     revision_count  integer NOT NULL DEFAULT 0,
     is_source_ai    integer NOT NULL DEFAULT 0,
     is_deleted      integer NOT NULL DEFAULT 0,
     created_at      text NOT NULL DEFAULT (${NOW}),
     updated_at      text NOT NULL DEFAULT (${NOW})
   )`,
  `CREATE TABLE IF NOT EXISTS decision_revisions (
     id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     decision_id     integer NOT NULL REFERENCES decision_records(id) ON DELETE CASCADE,
     previous_answer text NOT NULL,
     previous_notes  text,
     reason          text NOT NULL,
     revised_at      text NOT NULL DEFAULT (${NOW})
   )`,

  // ── task-scoped tables ──
  `CREATE TABLE IF NOT EXISTS task_git_context (
     task_id         integer PRIMARY KEY REFERENCES tasks(id),
     git_root_path   text NOT NULL,
     subrepo_path    text,
     branch_name     text,
     worktree_path   text,
     worktree_status text NOT NULL DEFAULT 'not_created',
     base_sha        text
   )`,
  `CREATE TABLE IF NOT EXISTS pending_messages (
     id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     task_id    integer NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
     content    text NOT NULL,
     created_at text NOT NULL DEFAULT (${NOW})
   )`,
  `CREATE TABLE IF NOT EXISTS task_hunk_decisions (
     task_id        integer NOT NULL REFERENCES tasks(id),
     hunk_hash      text NOT NULL,
     file_path      text NOT NULL,
     reviewer_type  text NOT NULL DEFAULT 'human',
     reviewer_id    text NOT NULL DEFAULT 'user',
     decision       text NOT NULL DEFAULT 'pending',
     comment        text,
     original_start integer NOT NULL DEFAULT 0,
     modified_start integer NOT NULL DEFAULT 0,
     created_at     text NOT NULL DEFAULT (${NOW}),
     updated_at     text NOT NULL DEFAULT (${NOW}),
     sent           integer NOT NULL DEFAULT 0,
     original_end   integer NOT NULL DEFAULT 0,
     modified_end   integer NOT NULL DEFAULT 0,
     PRIMARY KEY (task_id, hunk_hash, reviewer_id)
   )`,
  `CREATE TABLE IF NOT EXISTS task_line_comments (
     id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     task_id       integer NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
     file_path     text NOT NULL,
     line_start    integer NOT NULL,
     line_end      integer NOT NULL,
     line_text     text NOT NULL DEFAULT '[]',
     context_lines text NOT NULL DEFAULT '[]',
     comment       text NOT NULL,
     reviewer_id   text NOT NULL DEFAULT 'user',
     reviewer_type text NOT NULL DEFAULT 'human',
     sent          integer NOT NULL DEFAULT 0,
     created_at    text NOT NULL DEFAULT (${NOW}),
     col_start     integer NOT NULL DEFAULT 0,
     col_end       integer NOT NULL DEFAULT 0
   )`,
  `CREATE TABLE IF NOT EXISTS task_todos (
     id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     task_id     integer NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
     title       text NOT NULL,
     status      text NOT NULL DEFAULT 'not-started',
     result      text,
     created_at  text NOT NULL DEFAULT (${NOW}),
     updated_at  text NOT NULL DEFAULT (${NOW}),
     number      double precision NOT NULL DEFAULT 0,
     description text NOT NULL DEFAULT '',
     phase       text NULL
   )`,

  // ── execution-scoped ──
  `CREATE TABLE IF NOT EXISTS model_raw_messages (
     id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     task_id       integer NULL,
     execution_id  integer NOT NULL REFERENCES executions(id) ON DELETE CASCADE,
     engine        text NOT NULL,
     session_id    text,
     stream_seq    integer NOT NULL,
     direction     text NOT NULL,
     event_type    text NOT NULL,
     event_subtype text,
     payload_json  text NOT NULL,
     created_at    text NOT NULL DEFAULT (${NOW})
   )`,
  `CREATE TABLE IF NOT EXISTS task_execution_checkpoints (
     execution_id integer PRIMARY KEY REFERENCES executions(id),
     stash_ref    text,
     created_at   text NOT NULL DEFAULT (${NOW})
   )`,

  // ── conversation-scoped ──
  `CREATE TABLE IF NOT EXISTS chat_sessions (
     id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     workspace_key      text NOT NULL,
     title              text NOT NULL,
     status             text NOT NULL DEFAULT 'idle',
     conversation_id    integer NOT NULL UNIQUE REFERENCES conversations(id),
     last_activity_at   text NOT NULL DEFAULT (${NOW}),
     last_read_at       text NULL,
     archived_at        text NULL,
     created_at         text NOT NULL DEFAULT (${NOW}),
     enabled_mcp_tools  text NULL,
     shell_auto_approve integer NOT NULL DEFAULT 0,
     approved_commands  text NOT NULL DEFAULT '[]'
   )`,
  `CREATE TABLE IF NOT EXISTS task_notes (
     id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     conversation_id integer NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
     content         text NOT NULL,
     is_source_ai    integer NOT NULL DEFAULT 0,
     created_at      text NOT NULL DEFAULT (${NOW}),
     updated_at      text NOT NULL DEFAULT (${NOW}),
     tags            text NULL
   )`,
  `CREATE TABLE IF NOT EXISTS stream_events (
     id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     conversation_id integer NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
     execution_id    integer NOT NULL,
     seq             integer NOT NULL,
     block_id        text NOT NULL,
     type            text NOT NULL,
     content         text NOT NULL DEFAULT '',
     metadata        text,
     parent_block_id text,
     subagent_id     text,
     created_at      text DEFAULT (${NOW}),
     UNIQUE (conversation_id, seq)
   )`,

  // ── keyed / no-FK tables ──
  `CREATE TABLE IF NOT EXISTS enabled_models (
     workspace_key      text NOT NULL,
     qualified_model_id text NOT NULL,
     PRIMARY KEY (workspace_key, qualified_model_id)
   )`,
  `CREATE TABLE IF NOT EXISTS model_settings (
     workspace_key      text NOT NULL,
     qualified_model_id text NOT NULL,
     context_window     integer,
     PRIMARY KEY (workspace_key, qualified_model_id)
   )`,
  `CREATE TABLE IF NOT EXISTS conversation_injection_state (
     conversation_id                   integer NOT NULL,
     injection_type                    text NOT NULL,
     last_injected_after_compaction_id integer,
     PRIMARY KEY (conversation_id, injection_type)
   )`,
  `CREATE TABLE IF NOT EXISTS logs (
     id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     level        text NOT NULL DEFAULT 'info',
     task_id      integer,
     execution_id integer,
     message      text NOT NULL,
     data         text,
     created_at   text NOT NULL DEFAULT (${NOW})
   )`,

  // ── indexes ──
  `CREATE INDEX IF NOT EXISTS idx_tasks_board ON tasks(board_id)`,
  `CREATE INDEX IF NOT EXISTS idx_tasks_project ON tasks(project_key)`,
  `CREATE INDEX IF NOT EXISTS idx_tasks_board_state ON tasks(board_id, workflow_state)`,
  `CREATE INDEX IF NOT EXISTS idx_conversation_messages_conversation ON conversation_messages(conversation_id)`,
  `CREATE INDEX IF NOT EXISTS idx_executions_task ON executions(task_id)`,
  `CREATE INDEX IF NOT EXISTS idx_executions_conversation ON executions(conversation_id)`,
  `CREATE INDEX IF NOT EXISTS idx_executions_task_status_tokens ON executions(task_id, status, input_tokens)`,
  `CREATE INDEX IF NOT EXISTS idx_logs_task ON logs(task_id)`,
  `CREATE INDEX IF NOT EXISTS idx_logs_level ON logs(level)`,
  `CREATE INDEX IF NOT EXISTS idx_logs_execution ON logs(execution_id)`,
  `CREATE INDEX IF NOT EXISTS idx_logs_created ON logs(created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_hunk_decisions_task ON task_hunk_decisions(task_id)`,
  `CREATE INDEX IF NOT EXISTS idx_line_comments_task_file_sent ON task_line_comments(task_id, file_path, sent)`,
  `CREATE INDEX IF NOT EXISTS idx_pending_messages_task ON pending_messages(task_id)`,
  `CREATE INDEX IF NOT EXISTS idx_task_todos_task ON task_todos(task_id)`,
  `CREATE INDEX IF NOT EXISTS idx_task_notes_conversation ON task_notes(conversation_id)`,
  `CREATE INDEX IF NOT EXISTS idx_stream_events_conversation ON stream_events(conversation_id, seq)`,
  `CREATE INDEX IF NOT EXISTS idx_stream_events_execution ON stream_events(execution_id, seq)`,
  `CREATE INDEX IF NOT EXISTS idx_stream_events_conv_exec_seq ON stream_events(conversation_id, execution_id, seq)`,
  `CREATE INDEX IF NOT EXISTS idx_chat_sessions_workspace_activity ON chat_sessions(workspace_key, last_activity_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_model_raw_messages_execution_seq ON model_raw_messages(execution_id, stream_seq)`,
  `CREATE INDEX IF NOT EXISTS idx_model_raw_messages_task_created ON model_raw_messages(task_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_model_raw_messages_engine_type ON model_raw_messages(engine, event_type)`,
  `CREATE INDEX IF NOT EXISTS idx_decision_records_conversation_deleted ON decision_records(conversation_id, is_deleted)`,
  `CREATE INDEX IF NOT EXISTS idx_decision_revisions_decision_id ON decision_revisions(decision_id)`,
];

export async function up(db: Db): Promise<void> {
  for (const stmt of STATEMENTS) {
    await db.exec(stmt);
  }
}
