import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { isDockerAvailable, pgTestContainer, type PgFixture } from "./pg-test-container.ts";
import { PostgresDialect } from "../../db/dialect.ts";

describe.skipIf(!isDockerAvailable())("PostgreSQL dialect fragments execute for real (PC-3, PC-6)", () => {
  let fixture: PgFixture;
  const dialect = new PostgresDialect();

  beforeAll(async () => {
    fixture = await pgTestContainer();
    await fixture.db.exec(
      `CREATE TABLE t (
         id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         flag integer NOT NULL,
         metadata text,
         created_at text NOT NULL
       )`,
    );
  });

  afterAll(async () => {
    await fixture?.cleanup();
  });

  it("PG-D1: now() yields a valid, usable timestamp", async () => {
    const row = await fixture.db.get<{ ts: string }>(`SELECT ${dialect.now()} as ts`);
    expect(row?.ts).toMatch(/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/);
  });

  it("PG-D2: intervalAgo() produces a timestamp strictly before now()", async () => {
    const row = await fixture.db.get<{ now: string; past: string }>(
      `SELECT ${dialect.now()} as now, ${dialect.intervalAgo(1, "days")} as past`,
    );
    expect(row).toBeDefined();
    expect(new Date(row!.past + "Z").getTime()).toBeLessThan(new Date(row!.now + "Z").getTime());
  });

  it("PG-D3: jsonExtract() reads a nested JSON field", async () => {
    await fixture.db.exec(
      `INSERT INTO t (flag, metadata, created_at) VALUES (1, $1, ${dialect.now()})`,
      [JSON.stringify({ a: { b: "nested-value" } })],
    );
    const row = await fixture.db.get<{ v: string }>(
      `SELECT ${dialect.jsonExtract("metadata", "a.b")} as v FROM t WHERE flag = 1`,
    );
    expect(row?.v).toBe("nested-value");
  });

  it("PG-D4: returningId() reads the generated id back", async () => {
    const res = await fixture.db.exec(
      `INSERT INTO t (flag, created_at) VALUES (2, ${dialect.now()})${dialect.returningId()}`,
    );
    expect(res.rows[0]).toHaveProperty("id");
    expect(typeof (res.rows[0] as { id: unknown }).id).toBe("number");
  });

  it("PG-D5: boolean-like flag round-trips as a plain number (0/1), matching SQLite", async () => {
    await fixture.db.exec("INSERT INTO t (flag, created_at) VALUES ($1, " + dialect.now() + ")", [dialect.toDbBool(true)]);
    const row = await fixture.db.get<{ flag: number }>("SELECT flag FROM t WHERE flag = $1", [1]);
    expect(row?.flag).toBe(1);
    expect(dialect.fromDbBool(row?.flag)).toBe(true);
  });

  it("PG-D6: generated id is returned as a JS number, not bigint (no coercion needed — task 8.4)", async () => {
    const res = await fixture.db.exec(`INSERT INTO t (flag, created_at) VALUES (3, ${dialect.now()})${dialect.returningId()}`);
    const id = (res.rows[0] as { id: unknown }).id;
    expect(typeof id).toBe("number");
    expect(Number.isInteger(id)).toBe(true);
  });
});
